apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deployment
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: deployment
    spec:
      containers:
      - name: deployment
        image: kubelabs/tensorflow
